package shim

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/derekurban2001/authmux/internal/store"
)

func TestInstallAndRemove(t *testing.T) {
	dir := t.TempDir()
	p := store.Profile{Tool: store.ToolClaude, Name: "work"}
	path, err := Install(dir, p, "authmux")
	if err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(path); err != nil {
		t.Fatalf("shim not created: %v", err)
	}
	wantName := "claude-work"
	if runtime.GOOS == "windows" {
		wantName = "claude-work.cmd"
	}
	if filepath.Base(path) != wantName {
		t.Fatalf("unexpected shim name: %s", filepath.Base(path))
	}
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read shim: %v", err)
	}
	if !strings.Contains(string(content), "generated by authmux") {
		t.Fatalf("shim marker missing")
	}
	if err := Remove(dir, p); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Fatalf("shim should be removed")
	}
}

func TestInstallRemovesLegacyExtensionlessShimOnWindows(t *testing.T) {
	if runtime.GOOS != "windows" {
		t.Skip("windows-only behavior")
	}
	dir := t.TempDir()
	p := store.Profile{Tool: store.ToolCodex, Name: "work"}
	legacy := filepath.Join(dir, "codex-work")
	if err := os.WriteFile(legacy, []byte("# generated by authmux\n"), 0o755); err != nil {
		t.Fatal(err)
	}

	path, err := Install(dir, p, "authmux")
	if err != nil {
		t.Fatal(err)
	}
	if filepath.Base(path) != "codex-work.cmd" {
		t.Fatalf("expected .cmd shim, got %s", filepath.Base(path))
	}
	if _, err := os.Stat(legacy); !os.IsNotExist(err) {
		t.Fatalf("legacy extensionless shim should be removed")
	}
}
