package shim

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/derekurban/proflex-cli/internal/store"
)

const marker = "generated by proflex"

func DefaultShimDir() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".local", "bin"), nil
}

func Name(tool store.Tool, profile string) string {
	return fmt.Sprintf("%s-%s", tool, profile)
}

func Install(shimDir string, profile store.Profile, proflexBin string) (string, error) {
	if err := os.MkdirAll(shimDir, 0o755); err != nil {
		return "", err
	}
	baseName := Name(profile.Tool, profile.Name)
	shimPath := filepath.Join(shimDir, baseName)
	var content string
	if runtime.GOOS == "windows" {
		// Remove legacy extensionless shim so PowerShell resolves the .cmd wrapper.
		if err := os.Remove(shimPath); err != nil && !os.IsNotExist(err) {
			return "", err
		}
		shimPath += ".cmd"
		content = fmt.Sprintf(`@echo off
REM %s
setlocal
%s run %s %s -- %%*
exit /b %%ERRORLEVEL%%
`, marker, cmdQuote(proflexBin), profile.Tool, cmdQuote(profile.Name))
	} else {
		content = fmt.Sprintf(`#!/usr/bin/env bash
# %s
set -euo pipefail
exec %s run %s %s -- "$@"
`, marker, shellQuote(proflexBin), profile.Tool, shellQuote(profile.Name))
	}
	if err := os.WriteFile(shimPath, []byte(content), 0o755); err != nil {
		return "", err
	}
	return shimPath, nil
}

func Remove(shimDir string, profile store.Profile) error {
	base := filepath.Join(shimDir, Name(profile.Tool, profile.Name))
	paths := []string{base}
	if runtime.GOOS == "windows" {
		paths = append(paths, base+".cmd")
	}
	for _, path := range paths {
		if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
			return err
		}
	}
	return nil
}

func RemoveAll(shimDir string) ([]string, error) {
	entries, err := os.ReadDir(shimDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	removed := []string{}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if !(strings.HasPrefix(name, "claude-") || strings.HasPrefix(name, "codex-")) {
			continue
		}
		path := filepath.Join(shimDir, name)
		b, err := os.ReadFile(path)
		if err != nil {
			continue
		}
		if !strings.Contains(string(b), marker) {
			continue
		}
		if err := os.Remove(path); err == nil {
			removed = append(removed, path)
		}
	}
	return removed, nil
}

func shellQuote(s string) string {
	if s == "" {
		return "''"
	}
	return "'" + strings.ReplaceAll(s, "'", "'\\''") + "'"
}

func cmdQuote(s string) string {
	return `"` + strings.ReplaceAll(s, `"`, `""`) + `"`
}
