package shim

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/derekurban2001/authmux/internal/store"
)

const marker = "# generated by authmux"

func DefaultShimDir() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".local", "bin"), nil
}

func Name(tool store.Tool, profile string) string {
	return fmt.Sprintf("%s-%s", tool, profile)
}

func Install(shimDir string, profile store.Profile, authmuxBin string) (string, error) {
	if err := os.MkdirAll(shimDir, 0o755); err != nil {
		return "", err
	}
	shimPath := filepath.Join(shimDir, Name(profile.Tool, profile.Name))
	content := fmt.Sprintf(`#!/usr/bin/env bash
%s
set -euo pipefail
exec %s run %s %s -- "$@"
`, marker, shellQuote(authmuxBin), profile.Tool, shellQuote(profile.Name))
	if err := os.WriteFile(shimPath, []byte(content), 0o755); err != nil {
		return "", err
	}
	return shimPath, nil
}

func Remove(shimDir string, profile store.Profile) error {
	path := filepath.Join(shimDir, Name(profile.Tool, profile.Name))
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}

func RemoveAll(shimDir string) ([]string, error) {
	entries, err := os.ReadDir(shimDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	removed := []string{}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if !(strings.HasPrefix(name, "claude-") || strings.HasPrefix(name, "codex-")) {
			continue
		}
		path := filepath.Join(shimDir, name)
		b, err := os.ReadFile(path)
		if err != nil {
			continue
		}
		if !strings.Contains(string(b), marker) {
			continue
		}
		if err := os.Remove(path); err == nil {
			removed = append(removed, path)
		}
	}
	return removed, nil
}

func shellQuote(s string) string {
	if s == "" {
		return "''"
	}
	return "'" + strings.ReplaceAll(s, "'", "'\\''") + "'"
}
